name: foodrecipe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.0.0
  flutter_local_notifications: ^19.5.0
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^0.4.2
  path: ^1.9.1
  audioplayers: ^5.2.1
  vibration:
    path: packages/vibration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # ğŸ”¥ Localization
    - assets/lang/

    # ğŸ”¥ à¸«à¸¡à¸§à¸”à¸«à¸¡à¸¹à¹ˆ (à¸ªà¸³à¸„à¸±à¸à¸¡à¸²à¸ à¸•à¹‰à¸­à¸‡à¸›à¸£à¸°à¸à¸²à¸¨)
    - assets/data/
    - assets/data/country/

    # ğŸ”¥ à¸£à¸¹à¸›à¸ à¸²à¸à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”
    - assets/images/
    - assets/images/categories/
    - assets/images/cuisines/
    - assets/images/cuisines/chinese/
    - assets/images/cuisines/japanese/
    - assets/images/cuisines/korean/
    - assets/images/cuisines/thai/
    - assets/images/cuisines/american/
    - assets/images/cuisines/french/
    - assets/images/cuisines/greek/
    - assets/images/cuisines/indian/
    - assets/images/cuisines/italian/
    - assets/images/cuisines/mexican/
    - assets/images/cuisines/spanish/
    - assets/images/cuisines/turkish/
    - assets/images/cuisines/vietnamese/

    # ğŸ”¥ à¹€à¸ªà¸µà¸¢à¸‡
    - assets/sounds/alert.mp3
